INSERT INTO LABEL(id,description,date_create) VALUES('A09',"Infectious gastroenteritis and colitis, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('A64',"Unspecified sexually transmitted disease",now());
INSERT INTO LABEL(id,description,date_create) VALUES('B300',"Keratoconjunctivitis due to adenovirus",now());
INSERT INTO LABEL(id,description,date_create) VALUES('B302',"Viral pharyngoconjunctivitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('B308',"Other viral conjunctivitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('B309',"Viral conjunctivitis, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('B373',"Candlabeliasis of vulva and vagina",now());
INSERT INTO LABEL(id,description,date_create) VALUES('B9789',"Other viral agents as the cause of diseases classified elsewhere",now());
INSERT INTO LABEL(id,description,date_create) VALUES('E860',"Dehydration",now());
INSERT INTO LABEL(id,description,date_create) VALUES('F340',"Cyclothymic disorder",now());
INSERT INTO LABEL(id,description,date_create) VALUES('F341',"Dysthymic disorder",now());
INSERT INTO LABEL(id,description,date_create) VALUES('F39',"Unspecified mood [affective] disorder",now());
INSERT INTO LABEL(id,description,date_create) VALUES('F411',"Generalized anxiety disorder",now());
INSERT INTO LABEL(id,description,date_create) VALUES('F418',"Other specified anxiety disorders",now());
INSERT INTO LABEL(id,description,date_create) VALUES('F419',"Anxiety disorder, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('F4321',"Adjustment disorder with depressed mood",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43001',"Migraine without aura, not intractable, with status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43009',"Migraine without aura, not intractable, without status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43019',"Migraine without aura, intractable, without status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43501',"Persistent migraine aura without cerebral infarction, not intractable, with status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43509',"Persistent migraine aura without cerebral infarction, not intractable, without status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43519',"Persistent migraine aura without cerebral infarction, intractable, without status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43701',"Chronic migraine without aura, not intractable, with status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43709',"Chronic migraine without aura, not intractable, without status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43711',"Chronic migraine without aura, intractable, with status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43719',"Chronic migraine without aura, intractable, without status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43809',"Other migraine, not intractable, without status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43811',"Other migraine, intractable, with status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43819',"Other migraine, intractable, without status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43829',"Menstrual migraine, not intractable, without status migrainosus,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43909',"Migraine, unspecified, not intractable, without status migrainosus",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43911',"Migraine, unspecified, intractable, with status migrainosus",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G43919',"Migraine, unspecified, intractable, without status migrainosus",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G44209',"Tension-type headache, unspecified, not intractable,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G44219',"Episodic tension-type headache, not intractable",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G4700',"Insomnia, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G4701',"Insomnia due to medical condition",now());
INSERT INTO LABEL(id,description,date_create) VALUES('G5600',"Carpal tunnel syndrome, unspecified upper limb",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H10029',"Other mucopurulent conjunctivitis, unspecified eye",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H1033',"Unspecified acute conjunctivitis, bilateral",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H1044',"Vernal conjunctivitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H1045',"Other chronic allergic conjunctivitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H10509',"Unspecified blepharoconjunctivitis, unspecified eye",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H10819',"Pingueculitis, unspecified eye",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H1089',"Other conjunctivitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H109',"Unspecified conjunctivitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H6020',"Malignant otitis externa, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H60339',"Swimmer's ear, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H60399',"Other infective otitis externa, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H6500',"Acute serous otitis media, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H65119',"Acute and subacute allergic otitis media (mucolabel) (sanguinous) (serous), unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H65199',"Other acute nonsuppurative otitis media, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H6520',"Chronic serous otitis media, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H65499',"Other chronic nonsuppurative otitis media, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H6590',"Unspecified nonsuppurative otitis media, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H66009',"Acute suppurative otitis media without spontaneous rupture of ear drum, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H66019',"Acute suppurative otitis media with spontaneous rupture of ear drum, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H663X9',"Other chronic suppurative otitis media, unspecified ear",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H6640',"Suppurative otitis media, unspecified, unspecified ear,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('H6690',"Otitis media, unspecified, unspecified ear,",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J00',"Acute nasopharyngitis [common cold]",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J0100',"Acute maxillary sinusitis, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J0110',"Acute frontal sinusitis, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J0130',"Acute sphenolabelal sinusitis, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J0140',"Acute pansinusitis, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J0190',"Acute sinusitis, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J029',"Acute pharyngitis, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J060',"Acute laryngopharyngitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J069',"Acute upper respiratory infection, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J209',"Acute bronchitis, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J301',"Allergic rhinitis due to pollen",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J3081',"Allergic rhinitis due to animal (cat) (dog) hair and dander",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J36',"Peritonsillar abscess",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J40',"Bronchitis, not specified as acute or chronic",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J411',"Mucopurulent chronic bronchitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J42',"Unspecified chronic bronchitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J45901',"Unspecified asthma with (acute) exacerbation",now());
INSERT INTO LABEL(id,description,date_create) VALUES('J45902',"Unspecified asthma with status asthmaticus",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K210',"Gastro-esophageal reflux disease with esophagitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K219',"Gastro-esophageal reflux disease without esophagitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K2900',"Acute gastritis without bleeding",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K2920',"Alcoholic gastritis without bleeding",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K2960',"Other gastritis without bleeding",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K5900',"Constipation, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K5901',"Slow transit constipation",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K5902',"Outlet dysfunction constipation",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K649',"Unspecified hemorrholabels",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K8019',"Calculus of gallbladder with other cholecystitis with obstruction",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K8020',"Calculus of gallbladder without cholecystitis without obstruction",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K8021',"Calculus of gallbladder without cholecystitis with obstruction",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K8042',"Calculus of bile duct with acute cholecystitis without obstruction",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K8050',"Calculus of bile duct without cholangitis or cholecystitis without obstruction",now());
INSERT INTO LABEL(id,description,date_create) VALUES('K8051',"Calculus of bile duct without cholangitis or cholecystitis with obstruction",now());
INSERT INTO LABEL(id,description,date_create) VALUES('L240',"Irritant contact dermatitis due to detergents",now());
INSERT INTO LABEL(id,description,date_create) VALUES('L242',"Irritant contact dermatitis due to solvents",now());
INSERT INTO LABEL(id,description,date_create) VALUES('L250',"Unspecified contact dermatitis due to cosmetics",now());
INSERT INTO LABEL(id,description,date_create) VALUES('L251',"Unspecified contact dermatitis due to drugs in contact with skin",now());
INSERT INTO LABEL(id,description,date_create) VALUES('L253',"Unspecified contact dermatitis due to other chemical products",now());
INSERT INTO LABEL(id,description,date_create) VALUES('L255',"Unspecified contact dermatitis due to plants, except food",now());
INSERT INTO LABEL(id,description,date_create) VALUES('L259',"Unspecified contact dermatitis, unspecified cause",now());
INSERT INTO LABEL(id,description,date_create) VALUES('M25539',"Pain in unspecified wrist",now());
INSERT INTO LABEL(id,description,date_create) VALUES('M5430',"Sciatica, unspecified slabele",now());
INSERT INTO LABEL(id,description,date_create) VALUES('N730',"Acute parametritis and pelvic cellulitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('N733',"Female acute pelvic peritonitis",now());
INSERT INTO LABEL(id,description,date_create) VALUES('N739',"Female pelvic inflammatory disease, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('N912',"Amenorrhea, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('N920',"Excessive and frequent menstruation with regular cycle",now());
INSERT INTO LABEL(id,description,date_create) VALUES('N921',"Excessive and frequent menstruation with irregular cycle",now());
INSERT INTO LABEL(id,description,date_create) VALUES('N924',"Excessive bleeding in the premenopausal period",now());
INSERT INTO LABEL(id,description,date_create) VALUES('N930',"Postcoital and contact bleeding",now());
INSERT INTO LABEL(id,description,date_create) VALUES('N946',"Dysmenorrhea, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('R079',"Chest pain, unspecified",now());
INSERT INTO LABEL(id,description,date_create) VALUES('R109',"Unspecified abdominal pain",now());
INSERT INTO LABEL(id,description,date_create) VALUES('R21',"Rash and other nonspecific skin eruption",now());
INSERT INTO LABEL(id,description,date_create) VALUES('R42',"Dizziness and glabeldiness",now());
INSERT INTO LABEL(id,description,date_create) VALUES('S53449A',"Ulnar collateral ligament sprain of unspecified elbow, initial encounter",now());
INSERT INTO LABEL(id,description,date_create) VALUES('S63519A',"Sprain of carpal joint of unspecified wrist, initial encounter",now());
INSERT INTO LABEL(id,description,date_create) VALUES('S63599A',"Other specified sprain of unspecified wrist, initial encounter",now());
INSERT INTO LABEL(id,description,date_create) VALUES('S638X9A',"Sprain of other part of unspecified wrist and hand, initial encounter",now());
INSERT INTO LABEL(id,description,date_create) VALUES('S93419A',"Sprain of calcaneofibular ligament of unspecified ankle, initial encounter",now());
INSERT INTO LABEL(id,description,date_create) VALUES('S93429A',"Sprain of deltolabel ligament of unspecified ankle, initial encounter",now());
INSERT INTO LABEL(id,description,date_create) VALUES('S93439A',"Sprain of tibiofibular ligament of unspecified ankle, initial encounter",now());